export const Actiontypes={
    
GET_ALL_ITEM:"GET_ALL_ITEM",
GET_ITEM_DETAILS:"GET_ITEM_DETAILS",
SET_ITEM_LOADING:"SET_ITEM_LOADING",

//-------------------CART DATA & CONSTANT's -------------
GET_CART_ALL:"GET_CART_ALL",
INCREMENT_CART_QTY:"INCREMENT_CART_QTY",
DECREMENT_CART_QTY:"DECREMENT_CART_QTY",
DELETE_CART_ITEM:"DELETE_CART_ITEM",
SAVE_CART_DATA:"SAVE_CART_DATA",
SET_CART_LOADING:"SET_CART_LOADING",
ADD_ITEM_TO_CART:"ADD_ITEM_TO_CART",
UPDATE_CART_NAME:"UPDATE_CART_NAME",


MAKE_TOAST:"MAKE_TOAST"
};
